### ISSUE TITLE
IndexOutOfBounds at com.jeantessier.classreader.impl.Classfile.getRawClass(Classfile.java:200)

### ISSUE THREAD

**Issue by stroeter** [jeantessier/dependency-finder#3] opened 2018-05-11 08:44 UTC
Hello Jean,

  there seems to be an issue with the classfile parser within your last official release. I guess it's because of java 8 bytecode .

Best Regards,
  Thomas

	java.lang.IndexOutOfBoundsException: Index: 1612, Size: 441
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.jeantessier.classreader.impl.Classfile.getRawClass(Classfile.java:200)
	at com.jeantessier.classreader.impl.Classfile.getClassName(Classfile.java:204)
	at com.jeantessier.classreader.impl.Classfile.<init>(Classfile.java:104)
	at com.jeantessier.classreader.impl.Classfile.<init>(Classfile.java:74)
	at com.jeantessier.classreader.impl.DefaultClassfileFactory.create(DefaultClassfileFactory.java:41)
	at com.jeantessier.classreader.impl.DefaultClassfileFactory.create(DefaultClassfileFactory.java:39)
	at com.jeantessier.classreader.TransientClassfileLoader.load(TransientClassfileLoader.java:70)
	at com.jeantessier.classreader.ClassfileLoaderEventSource.load(ClassfileLoaderEventSource.java:133)
	at com.jeantessier.classreader.ZipClassfileLoader.load(ZipClassfileLoader.java:127)
	at com.jeantessier.classreader.JarClassfileLoader.load(JarClassfileLoader.java:53)
	at com.jeantessier.classreader.ClassfileLoaderEventSource.load(ClassfileLoaderEventSource.java:93)
	at com.jeantessier.classreader.ClassfileLoader.load(ClassfileLoader.java:55)
	at com.jeantessier.dependencyfinder.ant.DependencyExtractor.execute(DependencyExtractor.java:275)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)

**Comment by jeantessier** [comment] 2018-05-11 17:40
This is a duplicate of issue #2.  There is a fix on the `master` branch that I haven't gotten around to deploy as an official release.

**Comment by stroeter** [comment] 2018-05-11 19:35
Hi Jean, thank you for your fast reply. Mhh, an official release including this fix would be cool - or maybe a patched former release..

**Comment by jeantessier** [comment] 2018-05-11 21:19
Roger that.  But it'll be a few days before I can get to it...

**Comment by OlivierJaquemet** [comment] 2019-04-01 08:33
As explained by Jean in issue #4. this bug was probably definitely fixed with this commit in which exception were completely swallowed : https://github.com/jeantessier/dependency-finder/commit/a5de21f465e809015be3d3d73d863dfe8a44d5cd

@stroeter I think you can close the issue.

That said, I share your request for an official build :) @jeantessier if you could manage to do that, that would be really nice. not all user can take the time to checkout and build dependency-finder ;)

**Comment by jeantessier** [comment] 2019-04-02 07:22
I agree.  I will do my best to find some time real soon.  Last time I tried to generate a build, some of the steps had become stale.  I will close this issue when I have a build that fixes it.

**Comment by OlivierJaquemet** [comment] 2019-04-02 07:31
Last week I did a build on a Win10 computer for my own usage, and it indeed requires quite some manipulations (that werent necessary when i was using Win7+Cygwin).

My notes regarding this : 

- Download Java JDK 7 (required for internal sun XSLT processing class)
- Download Apache Ant 1.9.x (1.10.x requires Java 8)
- Download Apache Tomcat 7.0.x
- Start PowerShell and set following environment variables
  `$Env:JAVA_HOME = "C:\Path\To\jdk1.7.0\"`
  `$Env:PATH="$Env:JAVA_HOME\bin;$Env:PATH"` _this is one is to ensure the above JDK is used if another exist on classpath_
  `$Env:CATALINA_HOME="C:\Path\To\apache-tomcat-7.0\"`
- In PowerShell, in dependency-finder directory, run ant exec
  `C:\Path\To\bin\ant.bat exec`
  All Java build should be successfull, 
  Ignore the perl error
- Start you favorite linux distrib in WSL, with perl properly installed and ant available
- run `ant generateBin` to finish the build process

**Comment by jeantessier** [comment] 2019-04-06 07:36
Included in release 1.2.1-beta5.

**Closed by jeantessier** 2019-04-06 07:36 UTC
Labels: duplicate
